# Generated by Django 3.2.5 on 2022-03-12 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250)),
                ('item_price', models.IntegerField()),
                ('item_quantity_left', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=250)),
                ('supplier_location', models.CharField(max_length=250)),
                ('amount_left_to_be_paid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.IntegerField()),
                ('total_bill', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('item_ordered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplymanagement.inventoryitems')),
                ('ordered_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplymanagement.suppliers')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitems',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplymanagement.suppliers'),
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated_quantity', models.CharField(max_length=250)),
                ('donated_in_area', models.CharField(max_length=250)),
                ('donation_cost', models.IntegerField()),
                ('donation_date', models.DateTimeField()),
                ('donated_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplymanagement.inventoryitems')),
            ],
        ),
    ]
