# Generated by Django 3.2.5 on 2022-03-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplymanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer_value', models.IntegerField()),
                ('string_values', models.CharField(max_length=250)),
            ],
        ),
    ]
