# Generated by Django 3.2.5 on 2022-03-13 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplymanagement', '0002_temporary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temporary',
        ),
    ]
