# Generated by Django 3.2.5 on 2022-03-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplymanagement', '0003_delete_temporary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='donation_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_bill',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
