# Generated by Django 3.2.5 on 2022-03-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplymanagement', '0004_auto_20220313_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='donated_quantity',
            field=models.IntegerField(max_length=250),
        ),
    ]
